# Generated by Django 4.2 on 2024-09-01 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mailing_name',
            field=models.CharField(blank=True, help_text='Введите название рассылки', max_length=100, null=True, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('failure', 'Неуспешно')], max_length=20, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('60', 'Ежеминутно'), ('300', 'Каждые пять минут'), ('600', 'Каждые 10 минут')], help_text='Выберите периодичность рассылки', max_length=50, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата и время первой отправки рассылки'),
        ),
        migrations.CreateModel(
            name='MailingTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
