# Generated by Django 4.2 on 2024-09-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_mailing_name_alter_attempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='last_send_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней отправки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='next_send_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующей отправки'),
        ),
    ]
