# Generated by Django 4.2 on 2024-09-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_last_send_date_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingtry',
            options={'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronimic',
            field=models.CharField(blank=True, help_text='Введите отчество', max_length=70, null=True, verbose_name='Отчество'),
        ),
    ]
