# Generated by Django 4.2 on 2024-09-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailingtry_options_mailing_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(help_text='Выберите клиентов', to='mailing.client', verbose_name='Клиенты'),
        ),
    ]
