# Generated by Django 4.2 on 2024-09-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_mailing_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingtry',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='last_send_date_time',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='next_send_date_time',
        ),
        migrations.AlterField(
            model_name='client',
            name='patronimic',
            field=models.CharField(blank=True, help_text='Ввeдите отчество', max_length=70, null=True, verbose_name='Отчество'),
        ),
    ]
