# Generated by Django 4.2 on 2024-09-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_remove_mailing_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='mailing',
        ),
    ]
