# Generated by Django 4.2 on 2024-09-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_rename_message_message_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
        ),
    ]
