# Generated by Django 4.2 on 2024-09-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_message_mailing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingTry',
        ),
    ]
