# Generated by Django 4.2 on 2024-09-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_client_owner_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Могу просматривать любые рассылки'), ('can_view_users', 'Могу просматривать список пользователей'), ('can_block_users', 'Могу блокировать пользователей'), ('can_disable_mailings', 'Могу отключать рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
