# Generated by Django 4.2 on 2024-08-28 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название заголовка', max_length=200, verbose_name='Название заголовка')),
                ('slug', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL-адрес')),
                ('content', models.TextField(help_text='Описание блога', max_length=10000, verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='photo/blog', verbose_name='Фото')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('published', models.BooleanField(default=True, verbose_name='Признак публикации')),
                ('views_counter', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
